#28 Support multiple languages
atlp-rwanda/ecommerce-app-predators-bn pull request #1
Opened 2023-03-27 16:11 UTC by Muhet

2023-03-29 11:33 UTC, mukunzidd requested changes

2023-03-29 11:33 UTC, mukunzidd commented on locales/sp/translation.json
Will people know how the words in Spanish? Did you agree with the team on the languages?

2023-03-29 11:33 UTC, mukunzidd commented on locales/ch/translation.json
Isn't Chinese/Cantonese a stretch? @Muhet talk to the team first.

2023-03-29 11:33 UTC, mukunzidd commented on package.json
Wait and update your package.json file with the latest changes since the project setup also added it.

2023-03-29 11:33 UTC, mukunzidd commented on server.js
isn't there a better folder or files to configure this middleware outside of the entry point of the app. Like a middleware folder. Please check the project structure.

2023-03-29 11:34 UTC, mukunzidd commented
@Muhet also remove the square. brackets around the card number and the rest of the title.

2023-03-29 13:48 UTC, Muhet commented on server.js
okey i'll look into it

2023-03-29 13:57 UTC, Muhet commented on locales/sp/translation.json
> Will people know how the words in Spanish? Did you agree with the team on the languages?

I changed it. I remain with two. French and English

2023-03-29 13:58 UTC, Muhet commented on locales/ch/translation.json
We had a conversation and we agreed that we will use french and english

2023-03-29 20:09 UTC, chanceDira reviewed
Nice job @Muhet,
Work on these changes requested and resolve conflict, then we are good

2023-03-29 20:52 UTC, ALVINdimpos commented on server.js
> +    }
great job man

2023-03-30 09:52 UTC, Muhet commented on server.js
> +    }
thx

2023-03-30 11:00 UTC, ALVINdimpos reviewed
cul

2023-03-30 21:01 UTC, ALVINdimpos approved these changes

2023-03-30 21:01 UTC, M936-B approved these changes
Congratulations on the successful completion of your task

2023-03-30 21:13 UTC, faid-terence approved these changes
Well done @Muhet ,

2023-03-31 06:30 UTC, NTElissa approved these changes

2023-03-31 06:38 UTC, chanceDira approved these changes
Good work @Muhet

2023-03-31 06:41 UTC, Vanessa-bitega approved these changes

2023-03-31 06:43 UTC, yobuir approved these changes
@Muhet nice work

2023-03-31 07:49 UTC, mukunzidd approved these changes

2023-03-31 08:18 UTC, kagaba-etienne approved these changes
Good Job!!!

2023-03-31 09:10 UTC, merged