Ft reset password 32
atlp-rwanda/ecommerce-app-predators-bn pull request #19
Opened 2023-04-05 00:51 UTC by yobuir

#### What does this PR do?

Includes functionality where vendors or buyers can reset password in case they forgot it

#### Description of Task to be completed?

The vendor and the buyer should be able to request password reset link and the link will be emailed to the user email he/she used when creating an account and after receiving reset link he/she will be able to create new account  

#### What are the relevant pivotal tracker/Trello stories?

Trello Card : https://trello.com/c/aOENvPGS/32-reset-password

#### Screenshots (if appropriate)
N/A

2023-04-05 06:46 UTC, chanceDira requested changes
Good job @yobuir 
I left some feedback for you

2023-04-05 06:46 UTC, chanceDira commented on .dockerignore
> +npx sequelize-cli model:generate --name Vendors --attributes user_id:string,lastName:string,workingEmail:string,productCategory:string,description:string,addresses:string,city:string
Why do we have this command here?

2023-04-05 06:46 UTC, chanceDira commented on src/app.js
> +console.log(process.env.DATABASE_URL);
I think this console was for debugging purposes, we can omit it since we don't need it

2023-04-05 06:46 UTC, chanceDira commented on src/controller/authController.js
> +            code: 400,
Can we use Jsend format to structure our responses?

2023-04-05 07:04 UTC, yobuir commented
![](https://github.trello.services/images/mini-trello-icon.png) [Reset Password](https://trello.com/c/aOENvPGS/32-reset-password)

2023-04-07 08:03 UTC, ALVINdimpos commented on src/utils/sendEmail.js
> +        const transporter = nodemailer.createTransport({
great work yob! but we have different sendemail function it's better to use the same

2023-04-07 08:13 UTC, faid-terence approved these changes
Nice Work

2023-04-13 16:29 UTC, chanceDira requested changes
Nice work @yobuir , just few changes

2023-04-13 16:29 UTC, chanceDira commented on src/controller/authController.js
> +            subject: 'E-commerce Reset Password',
In the subject you can also add our team name, e.g: Predators E-commerce Reset Password

2023-04-13 16:29 UTC, chanceDira commented on src/controller/authController.js
> +                    <a href="${process.env.APP_URL}:${process.env.PORT}/api/user/reset-password/${token}">Reset password</a>
am afraid that at production this will fail due to APP_URL and PORT

2023-04-18 07:27 UTC, ALVINdimpos approved these changes

2023-04-18 07:43 UTC, chanceDira reviewed
Nice work @yobuir

2023-04-18 07:43 UTC, chanceDira commented on src/utils/passport.js
> +  // passport.use(
If we are not using code we can remove it.

2023-04-18 08:10 UTC, NTElissa reviewed
RGTM

2023-04-18 20:48 UTC, chanceDira approved these changes
Nice work

2023-04-18 20:48 UTC, merged