#36 Feature: update profile
atlp-rwanda/ecommerce-app-predators-bn pull request #24
Opened 2023-04-05 16:05 UTC by Muhet

2023-04-05 21:24 UTC, ALVINdimpos commented on src/app.js
> -  swaggerDefinition: swaggerOptions, // <-- add this line
remember to remove swagger here!

2023-04-06 07:56 UTC, bryan936M approved these changes
Nice work

2023-04-07 08:06 UTC, ALVINdimpos approved these changes

2023-04-08 07:27 UTC, Vanessa-bitega approved these changes

2023-04-13 12:53 UTC, kagaba-etienne commented on .sequelizerc
I think this change will raise an error " Can not use import statement outside module"

2023-04-13 12:53 UTC, kagaba-etienne commented on src/database/migrations/20230329225700-create-user.cjs
UpdatedAt and createdAt should be default

2023-04-13 12:53 UTC, kagaba-etienne commented on src/database/migrations/20230403191345-create-user.cjs
UpdatedAt and createdAt should be default

2023-04-13 12:53 UTC, kagaba-etienne commented on src/database/migrations/20230403191535-create-product.cjs
UpdatedAt and createdAt should be default

2023-04-13 12:53 UTC, kagaba-etienne commented on src/database/migrations/20230403191841-create-carts.cjs
UpdatedAt and createdAt should be default

2023-04-13 12:53 UTC, kagaba-etienne commented on src/database/migrations/20230403192058-create-cart-items.cjs
UpdatedAt and createdAt should be default

2023-04-13 12:53 UTC, kagaba-etienne commented on src/database/migrations/20230403192329-create-roles.cjs
UpdatedAt and createdAt should be default

2023-04-13 12:53 UTC, kagaba-etienne commented on src/database/seeders/20230403195829-User.cjs
UpdatedAt and createdAt should be default

2023-04-13 12:53 UTC, kagaba-etienne commented on src/database/seeders/20230403202838-Carts.cjs
UpdatedAt and createdAt should be default

2023-04-13 12:53 UTC, kagaba-etienne commented on src/database/seeders/20230403202849-Products.cjs
UpdatedAt and createdAt should be default

2023-04-13 12:53 UTC, kagaba-etienne commented on src/database/seeders/20230403202953-Cart_Items.cjs
UpdatedAt and createdAt should be default

2023-04-13 12:53 UTC, kagaba-etienne commented on src/database/seeders/20230403203144-ROLEs.cjs
UpdatedAt and createdAt should be default

2023-04-13 16:20 UTC, chanceDira requested changes
Good job @Muhet, Please take a look on the below comments

2023-04-13 16:20 UTC, chanceDira commented on README.md
> +Node.js CI
Why do we have "Node.js CI" as a title?

2023-04-13 16:20 UTC, chanceDira commented on package.json
> +    "start": "NODE_ENV=development nodemon --exec babel-node src/server.js",
why cross-env is removed in the start script?

2023-04-13 16:20 UTC, chanceDira commented on src/controller/profileController.js
> +        message: req.t('user_not_found_exception')
Here's a template of the Jsend format, you use it in your responses

{
    status : "success",
    data : {
        "post" : { "id" : 1, "title" : "A blog post", "body" : "Some useful content" }
     }
}

2023-04-13 16:20 UTC, chanceDira commented on src/controller/profileController.js
> +   if (decoded.id !== parseInt(id)) {// Check if authenticated user ID matches requested user ID
This is nice.

2023-04-13 16:20 UTC, chanceDira commented on src/database/migrations/20230403192329-create-roles.cjs
> +    await queryInterface.createTable('ROLEs', {
Can you correct the naming "ROLEs"?

2023-04-13 16:20 UTC, chanceDira commented on update.txt
> +// Updating user Profile
do we need this file?

2023-04-13 16:20 UTC, chanceDira commented on newtext.txt
> +name,
Can you clarify the usage of this file

2023-04-13 17:24 UTC, ALVINdimpos approved these changes

2023-04-14 13:25 UTC, yobuir approved these changes
nice work

2023-04-14 13:25 UTC, yobuir commented on src/app.js
> +app.use('/api', profileRoutes)
I think here you have deprecated routes for authRoute

2023-04-14 13:25 UTC, yobuir commented on src/controller/profileController.js
we were advised to use Jsend in returning responses

2023-04-14 19:04 UTC, Vanessa-bitega approved these changes

2023-04-17 07:35 UTC, Muhet commented on newtext.txt
> +name,
ohhh!, i didn't want to loose my data, so i created that file  so that i past my code in case i needed them it will be easier to get them back.

2023-04-17 07:35 UTC, Muhet commented on newtext.txt
> +name,
but i'm going to remove it

2023-04-17 08:10 UTC, Muhet commented on src/database/migrations/20230403192329-create-roles.cjs
> +    await queryInterface.createTable('ROLEs', {
if i change it will it not affect the database , ?

2023-04-17 08:11 UTC, Muhet commented on update.txt
> +// Updating user Profile
no

2023-04-17 10:59 UTC, NTElissa reviewed
Good progress

2023-04-18 20:44 UTC, Muhet reviewed
ok

2023-04-19 10:21 UTC, chanceDira approved these changes
Good job @Muhet

2023-04-19 10:22 UTC, merged