#3 feature: build signup endpoint
atlp-rwanda/ecommerce-app-predators-bn pull request #26
Opened 2023-04-14 10:17 UTC by bryan936M

#### What does this PR do?
- make a buyer signup functionality
#### Description of Task to be completed?
- create a signup route
- create a signup controller
- adjust user database table to suit requirements
#### How should this be manually tested?
- clone this repo
- after opening the repo locally, install dependencies
- run the following command in a terminal: npm run sev
- open postman and go to: 'http://localhost:3000/auth/buyer-signup'
- input a user's credentials. Ex:
- {"name": "sample_user ","email":"sample_user@email.com", "password": "sample_userPassword"}
#### What are the relevant pivotal tracker/Trello stories?
- visit my trello card: 'https://trello.com/c/xpXq1R1r'

2023-04-14 10:47 UTC, faid-terence approved these changes
Great Work @bryan936M

2023-04-14 19:02 UTC, Vanessa-bitega approved these changes

2023-04-16 20:44 UTC, Vanessa-bitega approved these changes

2023-04-17 09:18 UTC, Muhet requested changes, later dismissed
I've done good job,

2023-04-17 09:18 UTC, Muhet commented on src/controller/authController.js
> +    res.status(200).json({ message: user }); // /!\use jsend
Use jsend format

2023-04-19 08:40 UTC, bryan936M commented on src/controller/authController.js
> +    res.status(200).json({ message: user }); // /!\use jsend
Done

2023-04-19 09:28 UTC, Muhet approved these changes
greate

2023-04-19 09:35 UTC, chanceDira approved these changes
NIce work @bryan936M

2023-04-19 09:35 UTC, merged