#29 Product Listing Feature
atlp-rwanda/ecommerce-app-predators-bn pull request #31
Opened 2023-04-19 20:45 UTC by kagaba-etienne

### This PR does:
- Enables user to retrive list of available items
- Enables vendors to retrieve list of available items in his collection

2023-04-24 10:22 UTC, Muhet approved these changes
Greate job

2023-04-24 11:51 UTC, ALVINdimpos approved these changes

2023-04-25 07:54 UTC, chanceDira requested changes
Nice work @kagaba-etienne 
Just some changes you need to fix and conflicts

2023-04-25 07:54 UTC, chanceDira commented on src/database/migrations/20230403191535-create-product.cjs
> +        allowNull: false,
Solve this conflict

2023-04-25 07:54 UTC, chanceDira commented on src/database/migrations/20230403191535-create-product.cjs
> +<<<<<<< HEAD
conflict

2023-04-25 07:54 UTC, chanceDira commented on src/database/models/cart_items.js
> +<<<<<<< HEAD
conflict

2023-04-25 07:54 UTC, chanceDira commented on src/database/models/product.js
> +>>>>>>> 9b6b4a2 (feat(product-listing): create the product listing feature)
conflict

2023-04-25 07:54 UTC, chanceDira commented on src/database/models/user.js
> +<<<<<<< HEAD
conflict

2023-04-25 07:54 UTC, chanceDira commented on src/database/seeders/20230403202849-Products.cjs
> +<<<<<<< HEAD
conflict

2023-04-25 07:54 UTC, chanceDira commented on src/middleware/roles.js
>      return res.status(401).json({ message: "Token not provided" }); // assuming the token is sent in the Authorization header
Here you can use "Not authorized", let not use token keyword. some people might not be aware about it :)

2023-04-25 20:20 UTC, kagaba-etienne commented on src/middleware/roles.js
>      return res.status(401).json({ message: "Token not provided" }); // assuming the token is sent in the Authorization header
ooh, okay it is fine. I'll change it.

2023-04-27 07:44 UTC, kagaba-etienne reviewed
Done!

2023-04-27 07:52 UTC, ALVINdimpos approved these changes

2023-04-27 08:17 UTC, faid-terence approved these changes
Good Job @kagaba-etienne

2023-04-27 09:33 UTC, nili-alu approved these changes

2023-04-27 10:01 UTC, chanceDira approved these changes
Nice job @kagaba-etienne

2023-04-27 10:01 UTC, merged