Ft fix bugs from develop
atlp-rwanda/ecommerce-app-predators-bn pull request #37
Opened 2023-04-21 06:16 UTC by Muhet

#### What does this PR do?

#### Description of Task to be completed?
          To fix the conflict which was found in main branch
#### How should this be manually tested?
           everyone mush check his/her task if it is works
#### Any background context you want to provide?

#### What are the relevant pivotal tracker/Trello stories?

#### Screenshots (if appropriate)

#### Questions:

2023-04-21 14:47 UTC, NTElissa reviewed
squash commits

2023-04-24 12:34 UTC, nili-alu approved these changes

2023-04-24 12:34 UTC, nili-alu commented on src/routes/authRoutes.js
>  router.post('/logout', logout);
vendor route missed 
add these lines:
`import vendor from '../controller/vendorController.js';

router.post('/vendor',isAdmin, vendor);`

2023-04-24 12:37 UTC, nili-alu requested changes

2023-04-24 12:37 UTC, nili-alu commented on src/routes/authRoutes.js
>  router.post('/logout', logout);
vendor route missed, add the two lines:
import vendor from '../controller/vendorController.js';

router.post('/vendor',isAdmin, vendor);

2023-04-24 16:55 UTC, ALVINdimpos approved these changes

2023-04-24 19:56 UTC, vanessa-abewe approved these changes

2023-04-24 20:24 UTC, faid-terence approved these changes

2023-04-25 09:28 UTC, NTElissa approved these changes
good progress

2023-04-25 11:13 UTC, bryan936M approved these changes
All my codes are there

2023-04-25 17:50 UTC, kagaba-etienne reviewed
Nice

2023-04-25 17:52 UTC, kagaba-etienne approved these changes
Nice

2023-04-25 19:16 UTC, yobuir approved these changes

2023-04-25 19:47 UTC, nili-alu approved these changes

2023-04-26 07:19 UTC, chanceDira approved these changes
Good work

2023-04-26 07:19 UTC, merged