Implement update-product-from-collection feature (#33)
atlp-rwanda/ecommerce-app-predators-bn pull request #38
Opened 2023-04-21 07:30 UTC by ALVINdimpos

What does this PR do?

    This pull request implements the update-product-from-collection feature in the backend of the application.
    Description of Task to be completed

        Implement an API endpoint that updates a product in the collection based on user input.
        Add error handling to ensure that only valid data can be entered.
      
    How should this be manually tested?

        Start the backend server.
Run the following command to start the server: `npm run dev`
Send a PUT request to the update-product endpoint with valid input data:
`http://localhost:3000/api/v1/products/:id`
Verify that the response status code is 200 and the updated product information is returned:
{
    "status": "success",
    "message": "Product updated successfully",
    "data": {
        "id": 1,
        "name": "Samsung Galaxy S21",
        "description": "Samsung Galaxy S21 is a smartphone that was tested with the Android 11 operating system. This model weighs 6.2 ounces, has a 6.2-inch touch screen display, 12-megapixel main camera, and 10-megapixel selfie camera. It comes with 8GB of RAM.",
        "price": 1000,
        "quantity": 10,
        "image": "https://images-na.ssl-images-amazon.com/images/I/71ZtNda%2BguL._AC_SL1500_.jpg",
        "createdAt": "2021-03-01T14:00:00.000Z",
        "updatedAt": "2021-03-01T14:00:00.000Z"
    }
}
Send a PUT request with invalid input data and verify that the appropriate error response is returned:
{
    "status": "error",
    "message": "Validation error",
    "errors": [
        {
            "field": "name",
            "message": "Name is required"
        }
    ]
}

    Any background context you want to provide?

    This feature was requested by the product owner to improve the product management capabilities of the backend API.
    What are the relevant pivotal tracker stories?

        [#33] Implement 'update-product-from-collection' feature in backend API.

    Screenshots (if appropriate)

2023-04-21 11:07 UTC, ALVINdimpos commented
![](https://github.trello.services/images/mini-trello-icon.png) [A seller should be able to update an product item from their collection](https://trello.com/c/zfBEciKz/33-a-seller-should-be-able-to-update-an-product-item-from-their-collection)

2023-04-23 14:05 UTC, kagaba-etienne approved these changes
Great Job

2023-04-24 09:27 UTC, NTElissa approved these changes
good progress

2023-04-24 10:18 UTC, Muhet reviewed
Great work brother

2023-04-24 10:25 UTC, faid-terence approved these changes
Good Work

2023-04-24 11:50 UTC, Vanessa-bitega approved these changes

2023-04-24 12:17 UTC, nili-alu requested changes

2023-04-24 12:17 UTC, nili-alu commented on src/routes/authRoutes.js
>  router.post('/logout', logout);
you missed the vendor router ad that line 
```
import vendor from '../controller/vendorController.js';

router.post('/vendor',isAdmin, vendor);
```

2023-04-24 12:17 UTC, nili-alu commented on src/controller/vendorController.js
> -  const { name, email, gender, preferred_language, preferred_corrency } = req.body;
remove these line
`  const { name, email, gender, preferred_language, preferred_corrency } = req.body;`
`  if (!name || !email || !gender || !preferred_language, !preferred_corrency) {`

2023-04-24 12:17 UTC, nili-alu commented on src/controller/vendorController.js
> -      preferred_corrency,
remove this line

2023-04-24 16:05 UTC, yobuir approved these changes

2023-04-26 14:38 UTC, merged