#27 feature: recommend product to a buyer
atlp-rwanda/ecommerce-app-predators-bn pull request #42
Opened 2023-04-24 09:44 UTC by nili-alu

**What does this PR do?**

recommend products to the buyer

**Description of Task to be completed**

this PR will take the category_id of search products and return other products of the same category as recommended products 

**How should this be manually tested?**
clone this directory

1. open your terminal in Vscode 
- run `git clone https://github.com/atlp-rwanda/ecommerce-app-predators-bn.git`
- run `git checkout ft-recommendProduct-27`
- run `npm install`
- run `npm run dev`

2. open postman

-**example1:** past: [url](http://localhost:3000/api/product/all/search?keyword=google pixel)

- **example2:** past [url](http://localhost:3000/api/product/all/search?keyword=iPhone)

What are the relevant pivotal tracker stories?
[-card#27](https://trello.com/c/zJJHCwqi/27-buyer-should-be-able-to-see-recommended-products)

2023-04-24 09:47 UTC, NTElissa reviewed
good progress

2023-04-24 11:52 UTC, ALVINdimpos approved these changes

2023-04-24 22:19 UTC, NTElissa approved these changes
good progress

2023-04-26 14:30 UTC, yobuir approved these changes

2023-04-27 18:11 UTC, bryan936M approved these changes
Great work!

2023-04-27 22:12 UTC, chanceDira requested changes
Good job @nili-alu, just one thing

2023-04-27 22:12 UTC, chanceDira commented on draft/searchController.js
> +// import { Op } from "sequelize";
why do we need this draft folder

2023-04-28 07:39 UTC, nili-alu commented on draft/searchController.js
> +// import { Op } from "sequelize";
it was a mistake, removed

2023-04-28 08:04 UTC, Muhet approved these changes

2023-04-28 08:05 UTC, chanceDira approved these changes
Awesome @nili-alu

2023-04-28 08:05 UTC, merged