feat(notification): add in-app and email notifications for product lifecycle changes #5
atlp-rwanda/ecommerce-app-predators-bn pull request #47
Opened 2023-04-30 16:08 UTC by ALVINdimpos

What does this PR do?

    This PR implements notifications for product lifecycle changes. When a product is added, removed, expired, or bought, a notification will be sent to the vendor via email and in-app.
    Description of Task to be completed

        Set up cron jobs to listen for product lifecycle changes
        Implement Node events to trigger notifications for different types of product lifecycle changes
        Implement email notifications for vendors
        Implement in-app notifications for vendors

    How should this be manually tested?

        Create a product
        Verify that the vendor receives an email and in-app notification about the new product
        Update the product to simulate a lifecycle change (e.g. change the product status to "expired")
        Verify that the vendor receives an email and in-app notification about the product lifecycle change

    Any background context you want to provide?

    The notifications will be sent only to vendors who have opted in to receive them.
    What are the relevant pivotal tracker stories?

    N/A (or provide relevant pivotal tracker stories if applicable)
    Screenshots (if appropriate)

    N/A (or provide screenshots if appropriate)

2023-05-04 20:40 UTC, Muhet approved these changes

2023-05-05 19:47 UTC, Vanessa-bitega approved these changes

2023-05-06 17:13 UTC, chanceDira requested changes
Can you add commands to test you task and trello link

https://github.com/atlp-rwanda/engineering-playbook/wiki/3.-Pull-Request

2023-05-07 17:43 UTC, yobuir approved these changes

2023-05-07 20:07 UTC, chanceDira approved these changes
Nice job @ALVINdimpos

2023-05-07 20:07 UTC, merged