[24] [Ch setup testing environment]
atlp-rwanda/ecommerce-app-predators-bn pull request #5
Opened 2023-03-29 07:47 UTC by NTElissa

#### What does this PR do?
for testing  environment

#### Description of Task to be completed?

#### How should this be manually tested?

#### Any background context you want to provide?

#### What are the relevant pivotal tracker/Trello stories?

#### Screenshots (if appropriate)

#### Questions:

2023-03-29 20:18 UTC, chanceDira requested changes
Good progress, just some feedback also since you are using jest can you create a jest config file?

2023-03-29 20:18 UTC, chanceDira commented on README.md
> +# setup-continuous-integration-24
Why did you remove the title of the app?

2023-03-29 20:18 UTC, chanceDira commented on test/sample.js
> +
can you use the export default

2023-03-30 09:15 UTC, ALVINdimpos commented on tests/sample.js
> +  return a + b;
nice job ellisa

2023-03-30 09:19 UTC, Muhet approved these changes

2023-03-30 09:30 UTC, ALVINdimpos commented on tests/sample.test.js
> +
nice job

2023-03-30 10:49 UTC, Muhet approved these changes
Great Job

2023-03-30 19:24 UTC, faid-terence approved these changes

2023-03-30 21:46 UTC, ALVINdimpos approved these changes

2023-03-30 21:47 UTC, nili-alu approved these changes

2023-03-31 06:46 UTC, chanceDira approved these changes
Nice job @NTElissa

2023-03-31 06:49 UTC, M936-B approved these changes
Excellent work

2023-03-31 07:11 UTC, merged