fixed routes
atlp-rwanda/ecommerce-app-predators-bn pull request #50
Opened 2023-05-01 19:20 UTC by Vanessa-bitega

what does this PR do?
we fixed all the necessary routes

2023-05-01 19:24 UTC, faid-terence approved these changes

2023-05-02 04:09 UTC, chanceDira requested changes
Pull request is not descriptive enough, you can add other sections needed.

2023-05-02 06:09 UTC, Vanessa-bitega commented
> Done

2023-05-02 12:22 UTC, bryan936M approved these changes

2023-05-02 18:53 UTC, ALVINdimpos approved these changes

2023-05-02 19:00 UTC, Muhet approved these changes

2023-05-02 21:16 UTC, chanceDira approved these changes
Good work 👍🏽

2023-05-02 21:16 UTC, merged