#3 Create Checkout Flow
atlp-rwanda/ecommerce-app-predators-bn pull request #59
Opened 2023-05-04 10:12 UTC by kagaba-etienne

#### What does this PR do?
- Creates and order after checkout
- Calculates discount from applied coupons
#### Description of Task to be completed

> The backend needs to handle the checkout process, including validating and processing the order, updating inventory, and updating the customer's account.

#### How should this be manually tested?
- Checkout in branch `ft-checktout-3` and pull most recent changes
- Start the server by running `npm run start`
- Make sure you have a user account already, and few products in your cart before proceeding checkout.
- Make a POST request to this route `/api/checkout` with a requestBody containing the following properties `country, street_address, town, state, post_code, email` AKA billing information. Wait for a successful response. Kudos !!! You have just initiated an order.

#### Relevant pivotal tracker stories?
- [Card #3](https://trello.com/c/LUfLttI6)

2023-05-04 17:44 UTC, bryan936M approved these changes
Nice!

2023-05-05 16:06 UTC, ALVINdimpos approved these changes

2023-05-05 19:45 UTC, Vanessa-bitega approved these changes

2023-05-07 14:48 UTC, yobuir approved these changes
nice work #resolve_conflicts

2023-05-07 21:42 UTC, NTElissa approved these changes

2023-05-12 11:11 UTC, NTElissa reviewed
Good progress

2023-05-15 10:33 UTC, chanceDira requested changes
Good job @kagaba-etienne just one thing

2023-05-15 10:33 UTC, chanceDira commented on src/database/models/index.js
> +// if (config.use_env_variable) {
Remove these comments

2023-05-15 10:33 UTC, chanceDira commented on tests/Product.test.js
> +  // describe('DELETE api/product/:id', function() {
Remove these comments too

2023-05-15 18:25 UTC, chanceDira approved these changes
Good job @kagaba-etienne

2023-05-15 18:25 UTC, merged