translations-of-our-App
atlp-rwanda/ecommerce-app-predators-bn pull request #69
Opened 2023-05-18 11:52 UTC by Muhet

2023-05-25 17:59 UTC, ALVINdimpos approved these changes

2023-05-26 05:23 UTC, chanceDira requested changes
Fix the test and add description in your PR

2023-05-26 10:58 UTC, Vanessa-bitega approved these changes

2023-05-26 11:07 UTC, nili-alu approved these changes

2023-05-26 11:52 UTC, NTElissa approved these changes
good progress

2023-05-26 15:02 UTC, chanceDira approved these changes
Good work @Muhet

2023-05-26 15:02 UTC, merged