Ch- setup- docker- 26
atlp-rwanda/ecommerce-app-predators-bn pull request #7
Opened 2023-03-29 10:40 UTC by faid-terence

### What does the PR do?
Sets-up and created Dockerfile
I've created a Dockerfile for a Node.js application and I would like to contribute it to the project. This Dockerfile is based on the official Node.js image and includes all the necessary steps to build and run a Node.js application.
#### Description of Task to be completed?
1.An image of the backend application has been created
2.Database is running in a docker container
3.Both docker images can communicate while up and running locally
#### How should this be manually tested?
1.It starts with the official Node.js image as the base image.
2.It sets the working directory to /app and copies the package.json and package-lock.json files to the container.
3.It runs npm install to install the dependencies.
4.It copies the rest of the application files to the container.
5.It exposes port 3000 and sets the command to run the application using the npm start script.

### To build and run the container, you can use the following commands:
`docker build -t predators-ecommerce-app .
docker run -p 3000:3000 predators-ecommerce-app
`
#### What are the relevant pivotal tracker/Trello stories?
CardID: #26
cardLink: https://trello.com/c/cMwZJMBa/26-setup-docker
#### Screenshots (if appropriate)
**N/A**

2023-03-29 20:50 UTC, ALVINdimpos commented on routes/welcome.js
> +    res.status(200).send('Welcome to the Ecommerce RESTful API!');
great job faid

2023-03-30 06:21 UTC, chanceDira requested changes
Good progress @faid-terence, where is the docker-compose file?

2023-03-30 06:21 UTC, chanceDira commented on Dockerfile
> +# Define the command to run the application
Let's use "npm start"

2023-03-30 06:32 UTC, faid-terence commented
> Good progress @faid-terence, where is the docker-compose file?

Thanks @chanceDira , I have drafted a docker composé file but I haven't pushed it because we're waiting for database credentials from a person working on it , Hopefully by today it will done 
Thanks

2023-03-30 06:33 UTC, faid-terence commented on Dockerfile
> +# Define the command to run the application
> Let's use "npm start"

Alright it's Okay

2023-03-30 09:00 UTC, yobuir commented
> Good progress @faid-terence, where is the docker-compose file?

As @faid-terence mentioned we are working on the project image and we have the setup of `docker-compose` file which contains two images one for project and other for database

2023-03-30 10:06 UTC, faid-terence commented
![](https://github.trello.services/images/mini-trello-icon.png) [Setup Docker](https://trello.com/c/cMwZJMBa/26-setup-docker)

2023-03-30 18:55 UTC, yobuir approved these changes

2023-03-30 19:00 UTC, ALVINdimpos approved these changes

2023-03-30 19:42 UTC, ALVINdimpos approved these changes

2023-03-30 19:47 UTC, M936-B approved these changes

2023-03-31 07:41 UTC, chanceDira approved these changes
Good job @faid-terence @yobuir

2023-04-02 17:10 UTC, merged