Testing coverage
atlp-rwanda/ecommerce-app-predators-bn pull request #70
Opened 2023-05-19 10:08 UTC by yobuir

### What does this PR do?
This pull request adds unit tests to ensure that all routes in the application are functioning correctly. By doing so, we can catch any regressions that may occur as we continue to develop and maintain the application.

### Description of Task to be completed?
Ensure all Tests are Passing and Working as expected!

### How should this be manually tested?
To manually test  this, you can follow these steps:

`git clone https://github.com/atlp-rwanda/ecommerce-app-predators-bn.git`
```
run npm install
run npm run coverage
``` 

Screenshots (if appropriate)
N/A

2023-05-27 18:26 UTC, ALVINdimpos approved these changes

2023-05-28 18:18 UTC, Vanessa-bitega approved these changes

2023-05-28 20:25 UTC, Muhet requested changes
Why the test on push are not passing? if it is possible can you fix it?

2023-05-28 20:26 UTC, Muhet requested changes, later dismissed
Why the test on push are not passing? if it is possible can you fix it?

2023-05-29 22:49 UTC, faid-terence approved these changes

2023-05-30 04:34 UTC, NTElissa approved these changes
good progress

2023-05-30 08:04 UTC, chanceDira approved these changes
Nice work @yobuir just one thing

2023-05-30 08:04 UTC, chanceDira commented on .nyc_output/processinfo/index.json
> +<<<<<<< HEAD
Can you solve this issue, I think you got it while doing rebase

2023-05-30 08:04 UTC, chanceDira commented on tests/Admin.test.js
> +  // it('should return a JWT token on successful login', async () => {
If we are not using this we can delete these codes

2023-05-30 21:33 UTC, yobuir commented on .nyc_output/processinfo/index.json
> +<<<<<<< HEAD
fixed

2023-05-31 06:58 UTC, merged