#11 features: configure public live chat
atlp-rwanda/ecommerce-app-predators-bn pull request #71
Opened 2023-05-25 02:13 UTC by bryan936M

#### What does this PR do?
- add bi-directional and group chatting capability to the project
#### Description of Task to be completed?
- GIVEN the user is online
WHEN they open the chat tab
THEN they should be able to read all of the past chats
- GIVEN the user is online
WHEN they open the chat tab
THEN they should be able to post a public chat
- GIVEN the user
WHEN they post a chat
THEN it should be able to be echoed to all online users in real-time.
#### How should this be manually tested?
- Download this repo locally
- Open it and run 'npm run dev'
- go to 'http://localhost:3000/chat/chatRoom'
- open multiple tabs of chatRoom
- login(use a user saved in the db)
- then text publicly or join/create a private room
#### Any background context you want to provide?
- This uses the SOCKET.IO API for managing communication
- Shops on the website can own a private room easily
#### What are the relevant pivotal tracker/Trello stories?
Trello card: https://trello.com/c/cnpHM5zi
#### Screenshots (if appropriate)
#### Questions:

2023-05-25 17:45 UTC, Muhet approved these changes

2023-05-25 17:45 UTC, Muhet approved these changes

2023-05-25 17:59 UTC, ALVINdimpos approved these changes

2023-05-25 18:49 UTC, faid-terence approved these changes
Good Work

2023-05-25 23:01 UTC, NTElissa approved these changes
good progress

2023-05-26 05:08 UTC, chanceDira requested changes
Nice job @bryan936M, just one thing

2023-05-26 05:08 UTC, chanceDira commented on src/controller/chatController.js
> +      return res.status(201).json(room);
Can you apply the Jsend format in this file

2023-05-26 05:08 UTC, chanceDira commented on src/services/chatsDb.services.js
> +      console.error('Error saving chat instance:', error);
You can remove the log messages in this file

2023-05-29 08:30 UTC, chanceDira approved these changes
Good job @bryan936M

2023-05-29 08:31 UTC, merged