Hotfix/in app notification
atlp-rwanda/ecommerce-app-predators-bn pull request #88
Opened 2023-07-24 20:09 UTC by ALVINdimpos

2023-07-24 20:13 UTC, faid-terence approved these changes

2023-07-25 11:43 UTC, yobuir approved these changes

2023-07-25 17:14 UTC, bryan936M approved these changes

2023-07-26 08:59 UTC, chanceDira requested changes
Nice work, just one thing

2023-07-26 08:59 UTC, chanceDira commented on .nyc_output/processinfo/dce50d59-aae9-4c87-9b28-1efe2de63e38.json
> +{"parent":null,"pid":6879,"argv":["/usr/local/bin/node","/Users/andelarwanda/Desktop/ecommerce-app-predators-bn/node_modules/.bin/mocha","--config","./tests/.mocharc.cjs"],"execArgv":[],"cwd":"/Users
This file can be in .gitignore

2023-07-26 10:41 UTC, ALVINdimpos commented on .nyc_output/processinfo/dce50d59-aae9-4c87-9b28-1efe2de63e38.json
> +{"parent":null,"pid":6879,"argv":["/usr/local/bin/node","/Users/andelarwanda/Desktop/ecommerce-app-predators-bn/node_modules/.bin/mocha","--config","./tests/.mocharc.cjs"],"execArgv":[],"cwd":"/Users
solved!

2023-07-26 11:07 UTC, chanceDira commented on .nyc_output/processinfo/dce50d59-aae9-4c87-9b28-1efe2de63e38.json
> +{"parent":null,"pid":6879,"argv":["/usr/local/bin/node","/Users/andelarwanda/Desktop/ecommerce-app-predators-bn/node_modules/.bin/mocha","--config","./tests/.mocharc.cjs"],"execArgv":[],"cwd":"/Users
Cool.

2023-07-26 11:08 UTC, chanceDira approved these changes

2023-07-26 11:08 UTC, merged