Chore #37 setup environment variables
atlp-rwanda/ecommerce-app-predators-bn pull request #9
Opened 2023-03-29 22:20 UTC by nili-alu

Title:  setup environment variables
*description*
Setting up environment variable in dotenv file
What does this PR do?
[hidding sensitive information and also be able to notice the environment you are working in] Description of Task to be completed
[setup dotenv variables]
How should this be manually tested?
[running npm run (test or start or dev)]
Note: the variables in dotenv file are not correct will be replaced by actual value [Deliverables #37]

2023-03-30 06:06 UTC, ALVINdimpos commented on .env
> +DEV_DATABASE="postgress_url"
great job

2023-03-30 11:23 UTC, M936-B approved these changes
This is excelent work.
The completion of your task will allow us to make use of environment variables & all of their functionalities.
Your coding skills have been & will keep improving.

2023-03-30 16:33 UTC, yobuir approved these changes
great work

2023-03-30 16:33 UTC, yobuir commented on server.js
I think this variable `NODE_ENV` is not defined in .ENV file

2023-03-30 18:01 UTC, chanceDira requested changes
Good job @nili-alu @Vanessa-bitega , just some changes

2023-03-30 18:01 UTC, chanceDira commented on .env
> +NODE_ENV ={
why there is this "{" ?

2023-03-30 18:01 UTC, chanceDira commented on server.js
Yeah, exactly. @nili-alu @Vanessa-bitega you can find a value to put their

2023-03-30 19:07 UTC, nili-alu commented on .env
> +NODE_ENV ={
I used that to get all elements inside , this is how it looks 
NODE_ENV ={
        PRO_DATABASE="postgress_url"
        DEV_DATABASE="postgress_url"
        TEST_DATABASE="postgress_url"
}

2023-03-30 19:08 UTC, nili-alu commented on server.js
this is how it looks, NODE_ENV  is set of all links we will use
NODE_ENV ={
        PRO_DATABASE="postgress_url"
        DEV_DATABASE="postgress_url"
        TEST_DATABASE="postgress_url"
}

2023-03-30 19:46 UTC, ALVINdimpos approved these changes

2023-03-31 06:33 UTC, NTElissa approved these changes

2023-03-31 06:58 UTC, Muhet approved these changes

2023-03-31 08:17 UTC, kagaba-etienne approved these changes
This is good Lievin!!

2023-03-31 10:27 UTC, chanceDira commented on .env
> +NODE_ENV ={
can you use a variable name and a respective value as
e.g
NODE_ENV =development
PRO_DATABASE="postgress_url"
DEV_DATABASE="postgress_url"
TEST_DATABASE="postgress_url"

2023-03-31 11:26 UTC, nili-alu commented
no conflict now

2023-04-01 17:34 UTC, chanceDira approved these changes
Good work @nili-alu @Vanessa-bitega

2023-04-01 17:34 UTC, merged